name: Build & Deploy to Scaleway
on:
  push:
    branches: [main]
jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Build & Push client image to Scaleway Container Registry
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: "Create env file"
        run: |
          touch ./client/.env
          echo "${{ secrets.ENV_FILE_CLIENT }}" > ./client/.env
      - name: Build the CLIENT Docker image
        run: docker build ./client -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/client
      - name: Push the CLIENT Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/client
  build-server:
    runs-on: ubuntu-latest
    name: Build & Push server image to Scaleway Container Registry
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build the SERVER Docker image
        run: docker build ./server -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/server
      - name: Push the SERVER Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/server
  deploy-client:
    runs-on: ubuntu-latest
    needs: build-client
    name: Deploy client on Scaleway Containers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy client app to Scaleway
        id: deploy
        uses: httptoolkit/deploy-scaleway-serverless-container-action@v1
        with:
          timeout_seconds: 300
          container_id: fe605032-72a7-48df-94f3-e9b789fa8587
          secret_key: ${{ secrets.SECRET_KEY }}
          registry_image_url: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/client:latest
  deploy-server:
    runs-on: ubuntu-latest
    needs: build-server
    name: Deploy server on Scaleway Containers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy server app to Scaleway
        id: deploy_server
        uses: httptoolkit/deploy-scaleway-serverless-container-action@v1
        with:
          timeout_seconds: 300
          container_id: 760d0e0e-2430-45bc-9437-3a685118de14
          secret_key: ${{ secrets.SECRET_KEY }}
          registry_image_url: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/server:latest
